[server]
# Desabilita o encadeamento de pacotes que pode causar erro em redes instáveis
enableCORS = false
enableXsrfProtection = false

[browser]
# Tenta manter a conexão mais estável
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
fastReruns = false